name: ${project.name}
description: ${project.description}
author: ${plugin.author}
main: ${plugin.main-class}
version: ${project.version}
api-version: 1.13
softdepend: [ WorldGuard ]
permissions:
  bbush.fast:
    description: Access to fast growing
    default: op
  bbush.access:
    description: Access to bush
    default: true