name: ${project.name}
description: ${project.description}
author: ${plugin.author}
main: ${plugin.main-class}
version: ${project.version}
api-version: 1.13
depend: [ WorldEdit ]
permissions:
  bbush.fast:
    description: Доступ к быстрому выращеванию
    default: op
  bbush.access:
    description: Доступ к взаимодействию
    default: true